### PR TITLE
Mempool Streaming API

### PR DESCRIPTION
**Pull request by adityapk00**
New Mempool streaming API and implementation

### CODE REVIEW

**Comment by adityapk00** [comment]
cc: @LarryRuane @pacu @gmale

**Comment by LarryRuane** [comment]
Hi Aditya, this is great, thanks for contributing this. I tested it and it seems to work perfectly. 

Just after you mentioned this idea a month or two ago, I started implementing this myself (sorry for the lack of communication but I wasn't sure how far I'd get), but then I got distracted doing other things and put it aside. Seeing your PR, I looked again at those changes, and decided the best would be to combine our changes, which I did, please take a look at the latest commit on [this branch](https://github.com/LarryRuane/lightwalletd/commits/2021-07-19-mempool-stream). (I thought it would be simpler to make a commit instead of leaving lots of comments on this PR.) The main difference is that I avoided using goroutines, which are cool but somewhat complex to use and to verify the correctness of (in particular, that there are no race conditions). So the code in my branch is somewhat simpler but very similar. I tested this code but would encourage others to test too.

A small change I made which we may not want is I added a new [message type](https://github.com/LarryRuane/lightwalletd/commit/a3883a5d1aa7bbab6a33445508f7e859815d9390#diff-1e96986e4d8a5db61accb025e0e5f20feca968d67d26b5ccfedfa2c46b1582eaR41), `MempoolTransaction`. This is the same as the existing [`RawTransaction`](https://github.com/LarryRuane/lightwalletd/commit/a3883a5d1aa7bbab6a33445508f7e859815d9390#diff-1e96986e4d8a5db61accb025e0e5f20feca968d67d26b5ccfedfa2c46b1582eaR41) except it doesn't include a height. The comment for the `RawTransaction` height says that it should be -1 if the transaction is not yet mined. If it's always -1 for this gRPC, we may as well leave it off. I did leave the return as a JSON object (dictionary) so that we can add fields later if needed in a backward-compatible way. 

It would also be nice to have unit tests; I can work on those if you'd like.

If @gmale and @pacu haven't started using the inferior (non-streaming) mempool stuff that I pushed a while ago (the `GetMempoolTx` gRPC), we should also add a commit here to remove that stuff. I doubt anyone else has started using it.

**Comment by adityapk00** [comment]
This is great! I looked through your branch and tested it against Zecwallet, and it looks good to me. We can just use that, and close this PR. 

The one request I have is to use `RawTransaction` (with the height) instead of the `MempoolTransaction` type. It turns out I need the height (which will not be -1, but the height at which the tx was seen in the mempool), for various reasons in the client. 

If you're OK changing the API to return `RawTransaction` with `height = latestHeight`, that'll be fantastic!

I'm also OK removing the old mempool API.

**Comment by pacu** [comment]
@LarryRuane None of the other wallets we support or use our SDK use the mempool RPC

**Comment by LarryRuane** [comment]
> The one request I have is to use RawTransaction (with the height) ...

Yes, I just restored that (forced-pushed 01812b2e2fedd8d20edfc5f4508b138a50cc8ea2).

Instead of closing this PR, it would be less friction to just cherry-pick my commit into this PR (I haven't made my own PR yet, it's just a branch at the moment). Is that okay?

**Comment by adityapk00** [comment]
Sounds good. Will you take over this PR and add the tests as well? I'm not very familiar with Go testing.

**Review by LarryRuane — APPROVED** [review]
@adityapk00, I removed the old mempool code and added a unit test, could you please review? When it looks okay to you, I'll merge it (I don't have any further changes).

**Comment by adityapk00** [comment]
This looks great! Thanks for getting this done! 

Looks good to me!

**Comment by LarryRuane** [comment]
Rebased onto the latest master branch, force-pushed.

**Pull request merged**
