### PR TITLE
add GetLatestTreeState() grpc

### LINKED ISSUE #321: Feature request: GetLatestTreeState
### Quick summary:
`GetLatestTreeState` is to `GetTreeState` as `GetLatestBlock` is to `GetBlock`

### Feature Request:
As a wallet dev, I'd like to have a single call that gives me the latest sapling tree so that I can stick it in the wallet right before a release in order to make new wallets creation as fast as possible.

implementation notes:
-  this would simply get the latest block height and then pass that to the existing method for returning the tree state

### PR DESCRIPTION
**Pull request by LarryRuane**
Closes #321

### CODE REVIEW

**Comment by pacu** [comment]
@LarryRuane what's needed to close this one?

**Comment by geffenz** [comment]
Can we get clarity why this is needed @pacu? It has been added to a lightwalletd epic.

**Comment by defuse** [comment]
I can't remember but maybe it was for generating checkpoints?

**Comment by pacu** [comment]
Yes, it's for that, I thought this was already merged in.

**Comment by geffenz** [comment]
We could also use the -1 method on the block height to get the latest. Small enhancement required!

**Comment by LarryRuane** [comment]
Force-pushed to rebase onto latest `master` branch

**Pull request merged**
