### PR TITLE
Bring in latest `compact_formats.proto`

### PR DESCRIPTION
**Pull request by str4d**
From zcash/librustzcash@c13c8c667896e8089ad49e88d5c033f9e844ffc4, including the rework of how the commitment tree sizes are to be represented in CompactBlocks.

Please ensure this checklist is followed for any pull requests for this repo. This checklist must be checked by both the PR creator and by anyone who reviews the PR.
* [ ] Relevant documentation for this PR has to be completed before the PR can be merged
* [ ] A test plan for the PR must be documented in the PR notes and included in the test plan for the next regular release

As a note, all CI tests need to be passing and all appropriate code reviews need to be done before this PR can be merged

### CODE REVIEW

**Comment by str4d** [comment]
Currently a draft because I want https://github.com/zcash/librustzcash/pull/831 to merge before this (so I can ensure I'm referencing the correct commit).

**Comment by LarryRuane** [comment]
LGTM, @nick-ecc asked me to create a lightwalletd release, but I assume that should wait for this to merge?

**Comment by str4d** [comment]
@LarryRuane I've pulled in the last update from https://github.com/zcash/librustzcash/pull/831; this PR can be reviewed and merged now, and then the release cut.

**Comment by LarryRuane** [comment]
Testing turned up one problem, [force-pushed](https://github.com/zcash/lightwalletd/compare/6a2fb81b99a1a8a26a6857719c1fb87829831369..75c98a3398b3b2c6bd05bc22a73278dae3a91dd1) the fix. With protobuf, if a  message (struct) contains another message, the former points to an instance of the latter, rather than being inline. This pointer, within `CompactBlock` to `ChainMetadata` was not being initialized, so lightwalletd crashed with a segfault when trying to populate `ChainMetadata` in `common.go: getBlockFromRPC()`.

**Pull request merged**
